// Copyright (c) 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0
//
// SPDX-License-Identifier: EPL-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eclipse-kanto/container-management/containerm/sysinfo (interfaces: SystemInfoManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	types "github.com/eclipse-kanto/container-management/containerm/sysinfo/types"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSystemInfoManager is a mock of SystemInfoManager interface
type MockSystemInfoManager struct {
	ctrl     *gomock.Controller
	recorder *MockSystemInfoManagerMockRecorder
}

// MockSystemInfoManagerMockRecorder is the mock recorder for MockSystemInfoManager
type MockSystemInfoManagerMockRecorder struct {
	mock *MockSystemInfoManager
}

// NewMockSystemInfoManager creates a new mock instance
func NewMockSystemInfoManager(ctrl *gomock.Controller) *MockSystemInfoManager {
	mock := &MockSystemInfoManager{ctrl: ctrl}
	mock.recorder = &MockSystemInfoManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSystemInfoManager) EXPECT() *MockSystemInfoManagerMockRecorder {
	return m.recorder
}

// GetProjectInfo mocks base method
func (m *MockSystemInfoManager) GetProjectInfo() types.ProjectInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectInfo")
	ret0, _ := ret[0].(types.ProjectInfo)
	return ret0
}

// GetProjectInfo indicates an expected call of GetProjectInfo
func (mr *MockSystemInfoManagerMockRecorder) GetProjectInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectInfo", reflect.TypeOf((*MockSystemInfoManager)(nil).GetProjectInfo))
}
