// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/types/containers/container_config.proto

package containers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents the container's process configuration
type ContainerConfiguration struct {
	// Provides the environmental configuration of the container's process - i.e. environmental variables
	Env []string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty"`
	// Provides the command to be run upon container start
	Cmd                  []string `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerConfiguration) Reset()         { *m = ContainerConfiguration{} }
func (m *ContainerConfiguration) String() string { return proto.CompactTextString(m) }
func (*ContainerConfiguration) ProtoMessage()    {}
func (*ContainerConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed765160cde4af94, []int{0}
}

func (m *ContainerConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerConfiguration.Unmarshal(m, b)
}
func (m *ContainerConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerConfiguration.Marshal(b, m, deterministic)
}
func (m *ContainerConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerConfiguration.Merge(m, src)
}
func (m *ContainerConfiguration) XXX_Size() int {
	return xxx_messageInfo_ContainerConfiguration.Size(m)
}
func (m *ContainerConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerConfiguration proto.InternalMessageInfo

func (m *ContainerConfiguration) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ContainerConfiguration) GetCmd() []string {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func init() {
	proto.RegisterType((*ContainerConfiguration)(nil), "github.com.eclipse_kanto.container_management.containerm.api.types.containers.ContainerConfiguration")
}

func init() {
	proto.RegisterFile("api/types/containers/container_config.proto", fileDescriptor_ed765160cde4af94)
}

var fileDescriptor_ed765160cde4af94 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0x8b, 0xc2, 0x40,
	0x10, 0x85, 0xb9, 0x0b, 0x1c, 0x5c, 0xaa, 0x23, 0xc5, 0x91, 0x52, 0xac, 0x04, 0xc9, 0x6e, 0x61,
	0xa9, 0x95, 0xa9, 0x6d, 0xac, 0x24, 0x4d, 0xd8, 0x6c, 0xd6, 0xb8, 0xe8, 0xcc, 0x2c, 0xc9, 0x44,
	0xf0, 0xdf, 0x4b, 0x56, 0x65, 0x2c, 0xec, 0xde, 0x7c, 0x30, 0xbc, 0xef, 0xa5, 0x4b, 0x13, 0xbc,
	0xe6, 0x5b, 0x70, 0x83, 0xb6, 0x84, 0x6c, 0x3c, 0xba, 0xfe, 0x2d, 0xd6, 0x96, 0xf0, 0xe8, 0x3b,
	0x15, 0x7a, 0x62, 0xca, 0x76, 0x9d, 0xe7, 0xd3, 0xd8, 0x28, 0x4b, 0xa0, 0x9c, 0xbd, 0xf8, 0x30,
	0xb8, 0xfa, 0x6c, 0x90, 0x49, 0xc9, 0x03, 0x18, 0x34, 0x9d, 0x03, 0x87, 0x2c, 0x10, 0x94, 0x09,
	0x5e, 0xc5, 0x16, 0x81, 0xc3, 0x7c, 0x93, 0xfe, 0x97, 0xaf, 0xab, 0x8c, 0x3d, 0x63, 0x6f, 0xd8,
	0x13, 0x66, 0x7f, 0x69, 0xe2, 0xf0, 0x9a, 0x7f, 0xcd, 0x92, 0xc5, 0xef, 0x7e, 0x8a, 0x13, 0xb1,
	0xd0, 0xe6, 0xdf, 0x0f, 0x62, 0xa1, 0xdd, 0x56, 0xd5, 0x41, 0x74, 0xf4, 0x53, 0xa7, 0x88, 0x3a,
	0xe2, 0x5f, 0x88, 0x8e, 0x40, 0xd0, 0x9f, 0x46, 0xaf, 0x25, 0x36, 0x3f, 0x71, 0xef, 0xea, 0x1e,
	0x00, 0x00, 0xff, 0xff, 0xb8, 0xe4, 0xce, 0x2c, 0x1e, 0x01, 0x00, 0x00,
}
