// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/types/containers/hook.proto

package containers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a single runC hook
type Hook struct {
	// The path for the execution of the hook
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The hook arguments
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// The environmental variables needed for the hook
	Env []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	// Timeout for the hook's execution
	Timeout int32 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// The type of the Hook - prestart, poststart, poststop, etc.
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hook) Reset()         { *m = Hook{} }
func (m *Hook) String() string { return proto.CompactTextString(m) }
func (*Hook) ProtoMessage()    {}
func (*Hook) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c71640747bfd72, []int{0}
}

func (m *Hook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hook.Unmarshal(m, b)
}
func (m *Hook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hook.Marshal(b, m, deterministic)
}
func (m *Hook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hook.Merge(m, src)
}
func (m *Hook) XXX_Size() int {
	return xxx_messageInfo_Hook.Size(m)
}
func (m *Hook) XXX_DiscardUnknown() {
	xxx_messageInfo_Hook.DiscardUnknown(m)
}

var xxx_messageInfo_Hook proto.InternalMessageInfo

func (m *Hook) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Hook) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Hook) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Hook) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Hook) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*Hook)(nil), "github.com.eclipse_kanto.container_management.containerm.api.types.containers.Hook")
}

func init() {
	proto.RegisterFile("api/types/containers/hook.proto", fileDescriptor_b5c71640747bfd72)
}

var fileDescriptor_b5c71640747bfd72 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc7, 0x20,
	0x10, 0x40, 0x53, 0xdb, 0x9f, 0x46, 0x26, 0xc3, 0xc4, 0x66, 0xe3, 0xd4, 0xa5, 0x30, 0x38, 0xba,
	0x39, 0xb9, 0xb8, 0x74, 0x32, 0x5d, 0x9a, 0x6b, 0x73, 0x69, 0x49, 0x85, 0x23, 0xe5, 0x6a, 0xe2,
	0xb7, 0x37, 0xe0, 0x1f, 0x16, 0xb7, 0xc7, 0x0b, 0x1c, 0x79, 0x27, 0xee, 0x21, 0x58, 0xc3, 0x9f,
	0x01, 0xa3, 0x59, 0xc8, 0x33, 0x58, 0x8f, 0x47, 0x34, 0x1b, 0xd1, 0xae, 0xc3, 0x41, 0x4c, 0xf2,
	0x75, 0xb5, 0xbc, 0x9d, 0xb3, 0x5e, 0xc8, 0x69, 0x5c, 0xde, 0x6d, 0x88, 0x38, 0xed, 0xe0, 0x99,
	0xf4, 0xdf, 0xfd, 0xc9, 0x81, 0x87, 0x15, 0x1d, 0x7a, 0x2e, 0xd2, 0x69, 0x08, 0x56, 0xe7, 0xc9,
	0x45, 0xc6, 0x07, 0x2f, 0x9a, 0x17, 0xa2, 0x5d, 0x4a, 0xd1, 0x04, 0xe0, 0x4d, 0x55, 0x6d, 0xd5,
	0xdd, 0x0e, 0x99, 0x93, 0x83, 0x63, 0x8d, 0xea, 0xaa, 0xad, 0x93, 0x4b, 0x2c, 0xef, 0x44, 0x8d,
	0xfe, 0x43, 0xd5, 0x59, 0x25, 0x94, 0x4a, 0xdc, 0xb0, 0x75, 0x48, 0x27, 0xab, 0xa6, 0xad, 0xba,
	0xcb, 0xf0, 0x7b, 0x4c, 0xef, 0xd3, 0x7f, 0xea, 0xf2, 0x3d, 0x33, 0xf1, 0xf3, 0x38, 0xbe, 0x95,
	0x00, 0xf3, 0x13, 0xd0, 0xe7, 0x80, 0x12, 0xdc, 0x97, 0x80, 0x22, 0x9d, 0xf9, 0x6f, 0x35, 0x4f,
	0x05, 0xe7, 0xeb, 0xbc, 0xa1, 0xc7, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x83, 0x7f, 0xa3,
	0x44, 0x01, 0x00, 0x00,
}
