// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/types/containers/io_config.proto

package containers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// IO configuration contains the streams to be attached to this container
type IOConfig struct {
	// Whether to attach to `stderr`.
	AttachStderr bool `protobuf:"varint,1,opt,name=attach_stderr,json=attachStderr,proto3" json:"attach_stderr,omitempty"`
	// Whether to attach to `stdin`.
	AttachStdin bool `protobuf:"varint,2,opt,name=attach_stdin,json=attachStdin,proto3" json:"attach_stdin,omitempty"`
	// Whether to attach to `stdout`.
	AttachStdout bool `protobuf:"varint,3,opt,name=attach_stdout,json=attachStdout,proto3" json:"attach_stdout,omitempty"`
	// Open `stdin`
	OpenStdin bool `protobuf:"varint,4,opt,name=open_stdin,json=openStdin,proto3" json:"open_stdin,omitempty"`
	// Close `stdin` after one attached client disconnects
	StdinOnce bool `protobuf:"varint,5,opt,name=stdin_once,json=stdinOnce,proto3" json:"stdin_once,omitempty"`
	// Attach standard streams to a TTY, including `stdin` if it is not closed.
	Tty                  bool     `protobuf:"varint,6,opt,name=tty,proto3" json:"tty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IOConfig) Reset()         { *m = IOConfig{} }
func (m *IOConfig) String() string { return proto.CompactTextString(m) }
func (*IOConfig) ProtoMessage()    {}
func (*IOConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_59a8ea4abdf69641, []int{0}
}

func (m *IOConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IOConfig.Unmarshal(m, b)
}
func (m *IOConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IOConfig.Marshal(b, m, deterministic)
}
func (m *IOConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOConfig.Merge(m, src)
}
func (m *IOConfig) XXX_Size() int {
	return xxx_messageInfo_IOConfig.Size(m)
}
func (m *IOConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IOConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IOConfig proto.InternalMessageInfo

func (m *IOConfig) GetAttachStderr() bool {
	if m != nil {
		return m.AttachStderr
	}
	return false
}

func (m *IOConfig) GetAttachStdin() bool {
	if m != nil {
		return m.AttachStdin
	}
	return false
}

func (m *IOConfig) GetAttachStdout() bool {
	if m != nil {
		return m.AttachStdout
	}
	return false
}

func (m *IOConfig) GetOpenStdin() bool {
	if m != nil {
		return m.OpenStdin
	}
	return false
}

func (m *IOConfig) GetStdinOnce() bool {
	if m != nil {
		return m.StdinOnce
	}
	return false
}

func (m *IOConfig) GetTty() bool {
	if m != nil {
		return m.Tty
	}
	return false
}

func init() {
	proto.RegisterType((*IOConfig)(nil), "github.com.eclipse_kanto.container_management.containerm.api.types.containers.IOConfig")
}

func init() {
	proto.RegisterFile("api/types/containers/io_config.proto", fileDescriptor_59a8ea4abdf69641)
}

var fileDescriptor_59a8ea4abdf69641 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4b, 0x43, 0x31,
	0x14, 0xc5, 0x79, 0x56, 0x4b, 0x8d, 0x15, 0xe4, 0x4d, 0x6f, 0x29, 0xf8, 0x6f, 0x70, 0x69, 0x32,
	0x38, 0xba, 0xe9, 0xe4, 0x20, 0x05, 0x5d, 0xa4, 0x4b, 0x48, 0xe3, 0xf5, 0x35, 0x68, 0xee, 0x0d,
	0x2f, 0xf7, 0x0d, 0xfd, 0x84, 0x7e, 0x2d, 0xe9, 0x7d, 0xa5, 0x41, 0xe9, 0x76, 0xf9, 0x9d, 0x93,
	0x13, 0xf8, 0xa9, 0x5b, 0x97, 0x82, 0xe1, 0x4d, 0x82, 0x6c, 0x3c, 0x21, 0xbb, 0x80, 0xd0, 0x65,
	0x13, 0xc8, 0x7a, 0xc2, 0xcf, 0xd0, 0xea, 0xd4, 0x11, 0x53, 0xfd, 0xd2, 0x06, 0x5e, 0xf7, 0x2b,
	0xed, 0x29, 0x6a, 0xf0, 0xdf, 0x21, 0x65, 0xb0, 0x5f, 0x0e, 0x99, 0xf4, 0xfe, 0x91, 0x8d, 0x0e,
	0x5d, 0x0b, 0x11, 0x90, 0x0b, 0x8c, 0xda, 0xa5, 0xa0, 0x65, 0xbe, 0xc0, 0x7c, 0xfd, 0x53, 0xa9,
	0xc9, 0xf3, 0xe2, 0x49, 0x7e, 0xa8, 0x6f, 0xd4, 0xb9, 0x63, 0x76, 0x7e, 0x6d, 0x33, 0x7f, 0x40,
	0xd7, 0x35, 0xd5, 0x65, 0x75, 0x37, 0x79, 0x9d, 0x0e, 0xf0, 0x4d, 0x58, 0x7d, 0xa5, 0xa6, 0xa5,
	0x14, 0xb0, 0x39, 0x92, 0xce, 0xd9, 0xbe, 0x13, 0xf0, 0xef, 0x0e, 0xf5, 0xdc, 0x8c, 0xfe, 0xed,
	0x50, 0xcf, 0xf5, 0x4c, 0x29, 0x4a, 0x80, 0xbb, 0x95, 0x63, 0x69, 0x9c, 0x6e, 0xc9, 0xb0, 0x31,
	0x53, 0x4a, 0x12, 0x4b, 0xe8, 0xa1, 0x39, 0x19, 0x62, 0x21, 0x0b, 0xf4, 0x50, 0x5f, 0xa8, 0x11,
	0xf3, 0xa6, 0x19, 0x0b, 0xdf, 0x9e, 0x8f, 0xcb, 0xe5, 0x7b, 0x51, 0x63, 0x76, 0x6a, 0xe6, 0xa2,
	0xa6, 0xf8, 0x9c, 0x17, 0x35, 0x05, 0x46, 0x73, 0xc8, 0xfc, 0x43, 0x39, 0x57, 0x63, 0x71, 0x7f,
	0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xf8, 0xbe, 0x2a, 0xa3, 0x01, 0x00, 0x00,
}
