// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/types/containers/state.proto

package containers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// State represents a container's state
type State struct {
	// pid represents the container's process's PID
	Pid int64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// started_at defines the time when this container was last started
	StartedAt string `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// error indicates whether there was a problem that has occurred while changing the state of a container
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// exit_code represents the last exit code of the container's internal root process
	ExitCode int64 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// finished_at defines a timestamp of the last container's exit
	FinishedAt string `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// exited defines whether the container has exited on its own for some reason - daemon reboot or internal error - distinguishes between manual stop and internal exit
	Exited bool `protobuf:"varint,6,opt,name=exited,proto3" json:"exited,omitempty"`
	// dead identifies whether the underlying container is dead
	Dead bool `protobuf:"varint,7,opt,name=dead,proto3" json:"dead,omitempty"`
	// restarting identifies whether the underlying container is currently restarting
	Restarting bool `protobuf:"varint,8,opt,name=restarting,proto3" json:"restarting,omitempty"`
	// paused indicates whether this container is paused
	Paused bool `protobuf:"varint,9,opt,name=paused,proto3" json:"paused,omitempty"`
	// running indicates whether this container is running
	// Note: paused and running are not mutually exclusive as pausing actually requires the process to be running - it's only 'freezed' but still running
	Running bool `protobuf:"varint,10,opt,name=running,proto3" json:"running,omitempty"`
	// status represents the status of this container
	Status string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	// oomKilled indicates whether this container is killed due to out of memory
	OomKilled            bool     `protobuf:"varint,12,opt,name=oomKilled,proto3" json:"oomKilled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_babc1b1379d5533f, []int{0}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *State) GetStartedAt() string {
	if m != nil {
		return m.StartedAt
	}
	return ""
}

func (m *State) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *State) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *State) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

func (m *State) GetExited() bool {
	if m != nil {
		return m.Exited
	}
	return false
}

func (m *State) GetDead() bool {
	if m != nil {
		return m.Dead
	}
	return false
}

func (m *State) GetRestarting() bool {
	if m != nil {
		return m.Restarting
	}
	return false
}

func (m *State) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *State) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *State) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *State) GetOomKilled() bool {
	if m != nil {
		return m.OomKilled
	}
	return false
}

func init() {
	proto.RegisterType((*State)(nil), "github.com.eclipse_kanto.container_management.containerm.api.types.containers.State")
}

func init() {
	proto.RegisterFile("api/types/containers/state.proto", fileDescriptor_babc1b1379d5533f)
}

var fileDescriptor_babc1b1379d5533f = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0x23, 0x31,
	0x10, 0xc5, 0xb5, 0xf9, 0xbf, 0x93, 0x2b, 0x4e, 0xd6, 0xe9, 0x64, 0xe9, 0x0e, 0x58, 0x51, 0xa5,
	0xc9, 0x6e, 0x41, 0x49, 0x15, 0x28, 0x11, 0x4d, 0x68, 0x50, 0x9a, 0x95, 0xb3, 0x1e, 0x12, 0x8b,
	0xac, 0x6d, 0xd9, 0xb3, 0x12, 0x7c, 0x3b, 0x3e, 0x1a, 0xb2, 0x77, 0x83, 0x29, 0xe8, 0xe6, 0xfd,
	0xc6, 0xef, 0x69, 0xe4, 0x07, 0x85, 0xb0, 0xaa, 0xa2, 0x77, 0x8b, 0xbe, 0x6a, 0x8c, 0x26, 0xa1,
	0x34, 0x3a, 0x5f, 0x79, 0x12, 0x84, 0xa5, 0x75, 0x86, 0x0c, 0x7b, 0x3c, 0x28, 0x3a, 0x76, 0xfb,
	0xb2, 0x31, 0x6d, 0x89, 0xcd, 0x49, 0x59, 0x8f, 0xf5, 0xab, 0xd0, 0x64, 0xca, 0x2f, 0x43, 0xdd,
	0x0a, 0x2d, 0x0e, 0xd8, 0xa2, 0xa6, 0x04, 0xdb, 0x52, 0x58, 0x55, 0xc6, 0xe8, 0x04, 0xfd, 0xf5,
	0xc7, 0x08, 0xa6, 0x4f, 0x21, 0x9e, 0xfd, 0x86, 0xb1, 0x55, 0x92, 0x67, 0x45, 0xb6, 0x1a, 0x6f,
	0xc3, 0xc8, 0x2e, 0x00, 0x3c, 0x09, 0x47, 0x28, 0x6b, 0x41, 0x7c, 0x54, 0x64, 0xab, 0x7c, 0x9b,
	0x0f, 0x64, 0x43, 0xec, 0x0f, 0x4c, 0xd1, 0x39, 0xe3, 0xf8, 0x38, 0x6e, 0x7a, 0xc1, 0xfe, 0x41,
	0x8e, 0x6f, 0x8a, 0xea, 0xc6, 0x48, 0xe4, 0x93, 0x18, 0xb6, 0x08, 0xe0, 0xde, 0x48, 0x64, 0x57,
	0xb0, 0x7c, 0x51, 0x5a, 0xf9, 0x63, 0x1f, 0x39, 0x8d, 0x46, 0x38, 0xa3, 0x0d, 0xb1, 0xbf, 0x30,
	0x0b, 0x8f, 0x51, 0xf2, 0x59, 0x91, 0xad, 0x16, 0xdb, 0x41, 0x31, 0x06, 0x13, 0x89, 0x42, 0xf2,
	0x79, 0xa4, 0x71, 0x66, 0x97, 0x00, 0x0e, 0xe3, 0x39, 0x4a, 0x1f, 0xf8, 0x22, 0x6e, 0xbe, 0x91,
	0x90, 0x65, 0x45, 0xe7, 0x51, 0xf2, 0xbc, 0xcf, 0xea, 0x15, 0xe3, 0x30, 0x77, 0x9d, 0xd6, 0xc1,
	0x04, 0x71, 0x71, 0x96, 0xc1, 0x11, 0xbe, 0xba, 0xf3, 0x7c, 0x19, 0x2f, 0x1b, 0x14, 0xfb, 0x0f,
	0xb9, 0x31, 0xed, 0x83, 0x3a, 0x9d, 0x50, 0xf2, 0x5f, 0xd1, 0x93, 0xc0, 0xdd, 0x6e, 0xf7, 0x9c,
	0x3a, 0xa9, 0x86, 0x4e, 0xd6, 0xb1, 0x93, 0x54, 0xe2, 0x3a, 0x75, 0x92, 0x60, 0x5b, 0xfd, 0x54,
	0xf7, 0x6d, 0x1a, 0xf7, 0xb3, 0x58, 0xfa, 0xcd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xb7,
	0x47, 0x1b, 0x18, 0x02, 0x00, 0x00,
}
