// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/types/containers/stop_options.proto

package containers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// StopOptions represent options for stoping a container.
type StopOptions struct {
	// Timeout period in seconds to gracefully stop the container.
	Timeout int64 `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Force determines whether a SIGKILL signal will be send to the container's process if it does not finish within the timeout specified.
	Force bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	// Signal to be send to the container's process. Signal could be specified by using their names or numbers, e.g. SIGINT or 2.
	Signal               string   `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopOptions) Reset()         { *m = StopOptions{} }
func (m *StopOptions) String() string { return proto.CompactTextString(m) }
func (*StopOptions) ProtoMessage()    {}
func (*StopOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5fdd1ea0a788c41, []int{0}
}

func (m *StopOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopOptions.Unmarshal(m, b)
}
func (m *StopOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopOptions.Marshal(b, m, deterministic)
}
func (m *StopOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopOptions.Merge(m, src)
}
func (m *StopOptions) XXX_Size() int {
	return xxx_messageInfo_StopOptions.Size(m)
}
func (m *StopOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StopOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StopOptions proto.InternalMessageInfo

func (m *StopOptions) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *StopOptions) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *StopOptions) GetSignal() string {
	if m != nil {
		return m.Signal
	}
	return ""
}

func init() {
	proto.RegisterType((*StopOptions)(nil), "github.com.eclipse_kanto.container_management.containerm.api.types.containers.StopOptions")
}

func init() {
	proto.RegisterFile("api/types/containers/stop_options.proto", fileDescriptor_b5fdd1ea0a788c41)
}

var fileDescriptor_b5fdd1ea0a788c41 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0xc6, 0x89, 0x0f, 0x9f, 0x1a, 0xb7, 0x20, 0x92, 0xb1, 0xb8, 0xd8, 0xe5, 0x25, 0x83, 0xa3,
	0x9b, 0xbb, 0x08, 0x15, 0x41, 0xde, 0x52, 0xf2, 0xc2, 0x59, 0x0f, 0x9b, 0xdc, 0xd1, 0x5c, 0x07,
	0xff, 0x7b, 0xa1, 0xad, 0x66, 0x71, 0xcb, 0xf7, 0x83, 0xf0, 0xfd, 0xee, 0xd3, 0xf7, 0x81, 0xd1,
	0xcb, 0x37, 0x43, 0xf1, 0x91, 0xb2, 0x04, 0xcc, 0x30, 0x15, 0x5f, 0x84, 0xb8, 0x27, 0x16, 0xa4,
	0x5c, 0x1c, 0x4f, 0x24, 0x64, 0x9e, 0x07, 0x94, 0xcf, 0xf9, 0xe4, 0x22, 0x25, 0x07, 0x71, 0x44,
	0x2e, 0xd0, 0x7f, 0x85, 0x2c, 0xe4, 0xfe, 0xfe, 0xf5, 0x29, 0xe4, 0x30, 0x40, 0x82, 0x2c, 0x15,
	0x26, 0x17, 0x18, 0xdd, 0xd2, 0x50, 0x61, 0xb9, 0x7b, 0xd3, 0xd7, 0xaf, 0x42, 0xfc, 0xb2, 0x76,
	0x18, 0xab, 0x2f, 0x04, 0x13, 0xd0, 0x2c, 0x56, 0x35, 0xaa, 0xdd, 0x75, 0xbf, 0xd1, 0xdc, 0xe8,
	0xf3, 0x0f, 0x9a, 0x22, 0xd8, 0xb3, 0x46, 0xb5, 0x97, 0xdd, 0x1a, 0xcc, 0xad, 0xde, 0x17, 0x1c,
	0x72, 0x18, 0xed, 0xae, 0x51, 0xed, 0x55, 0xb7, 0xa5, 0xa7, 0xe3, 0xf1, 0xbd, 0x7a, 0xfa, 0xcd,
	0xf3, 0xb0, 0x78, 0xd6, 0xfb, 0x0e, 0xd5, 0xb3, 0xc2, 0xe4, 0xff, 0x5b, 0xe2, 0xb1, 0x3e, 0x4f,
	0xfb, 0x65, 0x88, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x2f, 0x7e, 0x52, 0x33, 0x01,
	0x00, 0x00,
}
