// Copyright (c) 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0
//
// SPDX-License-Identifier: EPL-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: containerm/network/net_mgr_api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/eclipse-kanto/container-management/containerm/containers/types"
	gomock "github.com/golang/mock/gomock"
)

// MockContainerNetworkManager is a mock of ContainerNetworkManager interface.
type MockContainerNetworkManager struct {
	ctrl     *gomock.Controller
	recorder *MockContainerNetworkManagerMockRecorder
}

// MockContainerNetworkManagerMockRecorder is the mock recorder for MockContainerNetworkManager.
type MockContainerNetworkManagerMockRecorder struct {
	mock *MockContainerNetworkManager
}

// NewMockContainerNetworkManager creates a new mock instance.
func NewMockContainerNetworkManager(ctrl *gomock.Controller) *MockContainerNetworkManager {
	mock := &MockContainerNetworkManager{ctrl: ctrl}
	mock.recorder = &MockContainerNetworkManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerNetworkManager) EXPECT() *MockContainerNetworkManagerMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockContainerNetworkManager) Connect(ctx context.Context, containers *types.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, containers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockContainerNetworkManagerMockRecorder) Connect(ctx, containers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockContainerNetworkManager)(nil).Connect), ctx, containers)
}

// Disconnect mocks base method.
func (m *MockContainerNetworkManager) Disconnect(ctx context.Context, container *types.Container, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect", ctx, container, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockContainerNetworkManagerMockRecorder) Disconnect(ctx, container, force interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockContainerNetworkManager)(nil).Disconnect), ctx, container, force)
}

// Dispose mocks base method.
func (m *MockContainerNetworkManager) Dispose(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispose", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dispose indicates an expected call of Dispose.
func (mr *MockContainerNetworkManagerMockRecorder) Dispose(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispose", reflect.TypeOf((*MockContainerNetworkManager)(nil).Dispose), ctx)
}

// Initialize mocks base method.
func (m *MockContainerNetworkManager) Initialize(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockContainerNetworkManagerMockRecorder) Initialize(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockContainerNetworkManager)(nil).Initialize), ctx)
}

// Manage mocks base method.
func (m *MockContainerNetworkManager) Manage(ctx context.Context, container *types.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manage", ctx, container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Manage indicates an expected call of Manage.
func (mr *MockContainerNetworkManagerMockRecorder) Manage(ctx, container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manage", reflect.TypeOf((*MockContainerNetworkManager)(nil).Manage), ctx, container)
}

// ReleaseNetworkResources mocks base method.
func (m *MockContainerNetworkManager) ReleaseNetworkResources(ctx context.Context, container *types.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseNetworkResources", ctx, container)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseNetworkResources indicates an expected call of ReleaseNetworkResources.
func (mr *MockContainerNetworkManagerMockRecorder) ReleaseNetworkResources(ctx, container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseNetworkResources", reflect.TypeOf((*MockContainerNetworkManager)(nil).ReleaseNetworkResources), ctx, container)
}

// Restore mocks base method.
func (m *MockContainerNetworkManager) Restore(ctx context.Context, container []*types.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockContainerNetworkManagerMockRecorder) Restore(ctx, container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockContainerNetworkManager)(nil).Restore), ctx, container)
}

// Stats mocks base method.
func (m *MockContainerNetworkManager) Stats(ctx context.Context, container *types.Container) (*types.IOStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, container)
	ret0, _ := ret[0].(*types.IOStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockContainerNetworkManagerMockRecorder) Stats(ctx, container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockContainerNetworkManager)(nil).Stats), ctx, container)
}
