// Copyright (c) 2021 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0
//
// SPDX-License-Identifier: EPL-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: containerm/ctr/ctrd_registries_resolver.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	remotes "github.com/containerd/containerd/remotes"
	gomock "github.com/golang/mock/gomock"
)

// MockcontainerImageRegistriesResolver is a mock of containerImageRegistriesResolver interface.
type MockcontainerImageRegistriesResolver struct {
	ctrl     *gomock.Controller
	recorder *MockcontainerImageRegistriesResolverMockRecorder
}

// MockcontainerImageRegistriesResolverMockRecorder is the mock recorder for MockcontainerImageRegistriesResolver.
type MockcontainerImageRegistriesResolverMockRecorder struct {
	mock *MockcontainerImageRegistriesResolver
}

// NewMockcontainerImageRegistriesResolver creates a new mock instance.
func NewMockcontainerImageRegistriesResolver(ctrl *gomock.Controller) *MockcontainerImageRegistriesResolver {
	mock := &MockcontainerImageRegistriesResolver{ctrl: ctrl}
	mock.recorder = &MockcontainerImageRegistriesResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcontainerImageRegistriesResolver) EXPECT() *MockcontainerImageRegistriesResolverMockRecorder {
	return m.recorder
}

// ResolveImageRegistry mocks base method.
func (m *MockcontainerImageRegistriesResolver) ResolveImageRegistry(imageRegistryHost string) remotes.Resolver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveImageRegistry", imageRegistryHost)
	ret0, _ := ret[0].(remotes.Resolver)
	return ret0
}

// ResolveImageRegistry indicates an expected call of ResolveImageRegistry.
func (mr *MockcontainerImageRegistriesResolverMockRecorder) ResolveImageRegistry(imageRegistryHost interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveImageRegistry", reflect.TypeOf((*MockcontainerImageRegistriesResolver)(nil).ResolveImageRegistry), imageRegistryHost)
}
