// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// https://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: ./containerm/ctr/ctrd_resource_watcher.go

// Package ctr is a generated GoMock package.
package ctr

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockresourcesWatcher is a mock of resourcesWatcher interface.
type MockresourcesWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockresourcesWatcherMockRecorder
}

// MockresourcesWatcherMockRecorder is the mock recorder for MockresourcesWatcher.
type MockresourcesWatcherMockRecorder struct {
	mock *MockresourcesWatcher
}

// NewMockresourcesWatcher creates a new mock instance.
func NewMockresourcesWatcher(ctrl *gomock.Controller) *MockresourcesWatcher {
	mock := &MockresourcesWatcher{ctrl: ctrl}
	mock.recorder = &MockresourcesWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresourcesWatcher) EXPECT() *MockresourcesWatcherMockRecorder {
	return m.recorder
}

// Dispose mocks base method.
func (m *MockresourcesWatcher) Dispose() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Dispose")
}

// Dispose indicates an expected call of Dispose.
func (mr *MockresourcesWatcherMockRecorder) Dispose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispose", reflect.TypeOf((*MockresourcesWatcher)(nil).Dispose))
}

// Watch mocks base method.
func (m *MockresourcesWatcher) Watch(resourceID string, duration time.Duration, expiredHandler watchExpired) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", resourceID, duration, expiredHandler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockresourcesWatcherMockRecorder) Watch(resourceID, duration, expiredHandler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockresourcesWatcher)(nil).Watch), resourceID, duration, expiredHandler)
}
